### ISSUE TITLE
Add a UI option or command to toggle the mod

### ISSUE THREAD

**Issue by YTThatOneGuy** [boomboompower/SkinChanger#28]
**Brief Summary:**
When nicked in-game, allow for the mod to be disabled so an MVP++ or YouTube Rank player can see the skin that is provided with their nick.

**Usage:**
1. Player does /nick and sets a name and skin
2. Player can see the skin from the nick (sent by the server)
3. Player can open GUI or run command override that skin, and show the player's original skin and cape.

**Justification:**
This would be useful for players who like the functionality of nickhider, but wishes that they could set **any** client-side skin on their stream/video.

Nickhider is not compatible with capes so there would be demand for this mod. 

People who play mega walls would benefit from being able to see the skin that is associated with their class.

**Comment by boomboompower** [comment]
I'll add a global toggle for the mod in the settings menu, and add a command alias for that in the next beta ^^

At the moment revert is the closeted current implementation. I have some ideas about how to do this and it shouldn't be too difficult - thanks for the suggestion.

**Comment by YTThatOneGuy** [comment]
> 
> 
> I'll add a global toggle for the mod in the settings menu, and add a command alias for that in the next beta ^^
> 
> At the moment revert is the closeted current implementation. I have some ideas about how to do this and it shouldn't be too difficult - thanks for the suggestion.

Thank you! I'm a fan of the mod but that's the one feature I can't do without 👍 

I can't really do much in return but - would you appreciate a youtube mod showcase?

**Comment by boomboompower** [comment]
> > I'll add a global toggle for the mod in the settings menu, and add a command alias for that in the next beta ^^
> > At the moment revert is the closeted current implementation. I have some ideas about how to do this and it shouldn't be too difficult - thanks for the suggestion.
> 
> Thank you! I'm a fan of the mod but that's the one feature I can't do without 👍
> 
> I can't really do much in return but - would you appreciate a youtube mod showcase?

Yeah sure - once it's done that'd be fantastic 👍 

Maybe not at the moment though - there's a lot of changes I'd still like to make to the current menus - thank you :)

**Comment by YTThatOneGuy** [comment]
> 
> 
> > > I'll add a global toggle for the mod in the settings menu, and add a command alias for that in the next beta ^^
> > > At the moment revert is the closeted current implementation. I have some ideas about how to do this and it shouldn't be too difficult - thanks for the suggestion.
> > 
> > 
> > Thank you! I'm a fan of the mod but that's the one feature I can't do without 👍
> > I can't really do much in return but - would you appreciate a youtube mod showcase?
> 
> Yeah sure - once it's done that'd be fantastic 👍
> 
> Maybe not at the moment though - there's a lot of changes I'd still like to make to the current menus - thank you :)

All good! Shoot me a message when you're done! If you've got discord I can be reached at That One Guy#2699

**Comment by boomboompower** [comment]
Command toggle will come in a later release, for now it's available through the settings menu

@YTThatOneGuy

**Comment by boomboompower** [comment]
## RE: Command to toggle

Doing `/skinchanger toggle` will now toggle the mod entirely (only functional when patches are enabled).

**Referenced Commits:**
* https://github.com/boomboompower/SkinChanger/commit/272e28bcb0a1765c77ccd4310ad7d22e638b6ee1

**Referenced Release:**
* [SkinChanger v3.0.78](https://github.com/boomboompower/SkinChanger/releases)
